version: "2"

services:
  mssql:
    image: microsoft/mssql-server-linux
    volumes:
      - mssql-volume:/var/opt/mssql
    restart: on-failure
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=pass
    ports:
      - "1433:1433"

volumes:
  mssql-volume: