version: "3"
services:
  postgres:
    image: 'postgres:12-alpine'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB : db_name
    ports:
        - "5432:5432"
    restart: on-failure