version: '2'

services:
  rabbit:
    container_name: rabbitmq-test
    hostname: rabbit
    build: .
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=test
    ports:
      - "5672:5672"
      - "15672:15672"
