version: '3'
services:
  mongodb:
    image: mongo:3.5
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    restart: on-failure
    ports:
      - 27017:27017
    volumes:
      - ./mongodb:/data/db