version: '2.1'
services:
  kong-database:
    image: postgres:9.6-alpine
    container_name: agw-db-kong
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
    ports:
      - "5432:5432"
    volumes:
      - ./storage/database/kong:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: on-failure
  kong-migration:
    image: kong:0.14.1-alpine
    container_name: agw-migration
    depends_on:
      kong-database:
        condition: service_healthy
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
    command: kong migrations up
    restart: on-failure
  kong:
    image: kong:0.14.1-alpine
    container_name: agw-kong
    depends_on:
      kong-database:
        condition: service_healthy
      kong-migration:
        condition: service_started
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_DATABASE=kong
      - KONG_ADMIN_LISTEN=0.0.0.0:8001        
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8443:8443"
      - "8444:8444"
    restart: on-failure
  konga-database:
    image: postgres:9.6-alpine
    container_name: agw-db-konga
    environment:
      - POSTGRES_USER=konga
      - POSTGRES_DB=konga
    ports:
      - "5433:5432"
    volumes:
      - ./storage/database/konga:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: on-failure
  konga:
    image: pantsel/konga:0.12.2
    container_name: agw-konga
    depends_on:
      konga-database:
        condition: service_healthy
    environment:
      - NODE_ENV=development
      - DB_ADAPTER=postgres
      - DB_HOST=agw-db-konga
      - DB_PORT=5432
      - DB_USER=konga
      - DB_PASSWORD=konga
      - DB_DATABASE=konga
    ports:
      - "1337:1337"