---
version: '3'
services:
    zookeeper:
        image: wurstmeister/zookeeper
        ports:
            - "2181:2181"
        networks:
            back-tier:
    kafka:
        image: wurstmeister/kafka
        # hostname: kafka
        ports:
            - "9092:9092"
        depends_on:
            - zookeeper
        environment:
            # KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://0.0.0.0:9092
            KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
            # KAFKA_CREATE_TOPICS: "test:1:1"
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ZOOKEEPER_TIMEOUT_MS: 36000
            # KAFKA_RETENTION_MS: 1000
            # KAFKA_LOG_RETENTION_MS: 1000
            # KAFKA_LOG_RETENTION_HOURS: 1
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            back-tier:

    # schema_registry:
    #     image: confluentinc/cp-schema-registry
    #     hostname: schema_registry
    #     depends_on:
    #         - zookeeper
    #         - kafka
    #     ports:
    #         - "8081:8081"
    #     environment:
    #         SCHEMA_REGISTRY_HOST_NAME: schema_registry
    #         SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:2181
    #     networks:
    #         back-tier:

    # schema_registry_ui:
    #     image: landoop/schema-registry-ui:0.9.4
    #     hostname: schema_registry_ui
    #     ports:
    #         - "8001:8000"
    #     environment:
    #         SCHEMAREGISTRY_URL: http://schema_registry:8081
    #         PROXY: 'true'
    #     depends_on:
    #         - schema_registry
    #     networks:
    #         back-tier:

    # rest_proxy:
    #     image: confluentinc/cp-kafka-rest:latest
    #     hostname: rest_proxy
    #     depends_on:
    #         - zookeeper
    #         - kafka
    #         - schema_registry
    #     ports:
    #         - "8082:8082"
    #     environment:
    #         KAFKA_REST_ZOOKEEPER_CONNECT: zookeeper:2181
    #         KAFKA_REST_LISTENERS: http://0.0.0.0:8082
    #         KAFKA_REST_SCHEMA_REGISTRY_URL: http://schema_registry:8081
    #         KAFKA_REST_HOST_NAME: rest_proxy
    #         KAFKA_REST_BOOTSTRAP_SERVERS: PLAINTEXT://127.0.0.1:9092
    #         KAFKA_REST_CONSUMER_REQUEST_TIMEOUT_MS: 30000
    #         KAFKA_REST_ACCESS_CONTROL_ALLOW_METHODS: 'GET,POST,PUT,DELETE,OPTIONS'
    #         KAFKA_REST_ACCESS_CONTROL_ALLOW_ORIGN: '*'
    #     networks:
    #         back-tier:

    # topics_ui:
    #     image: landoop/kafka-topics-ui:0.9.3
    #     hostname: topics_ui
    #     ports:
    #         - "8000:8000"
    #     environment:
    #         KAFKA_REST_PROXY_URL: http://rest_proxy:8082
    #         SCHEMAREGISTRY_UI_URL: http://schema_registry:8081
    #         PROXY: 'true'
    #     depends_on:
    #         - zookeeper
    #         - kafka
    #         - schema_registry
    #         - rest_proxy
    #     networks:
    #         back-tier:
networks:
  back-tier: