---
version: '3'
services:
  nsqlookupd:
    image: nsqio/nsq
    command: >
      /nsqlookupd
      -broadcast-address localhost:4160
    ports:
      - "4160:4160"
      - "4161:4161"
  nsqd:
    image: nsqio/nsq
    command: >
      /nsqd
      -broadcast-address localhost
      -lookupd-tcp-address nsqlookupd:4160
    ports:
      - "4150:4150"
      - "4151:4151"
  nsqadmin:
      image: nsqio/nsq
      command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
      depends_on:
        - nsqlookupd
      ports:
        - "4171:4171"